name: yugioh
description: "Yu-Gi-Oh!"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  intl: ^0.18.1
  package_info_plus: ^5.0.1
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  url_launcher: ^6.2.2
  gap: ^3.0.1
  oktoast: ^3.4.0
  percent_indicator: ^4.2.3
  device_info_plus: ^9.1.1
  mocktail: ^1.0.2
  bloc_test: ^9.1.5
  dio: ^5.4.0
  fullscreen_image_viewer: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/animations/loading/
  - assets/image/